# Generated by Django 5.0.4 on 2024-06-28 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=30)),
                ('order_name', models.CharField(max_length=30)),
                ('fat', models.IntegerField()),
                ('carb', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('carb_min', models.IntegerField()),
                ('carb_max', models.IntegerField()),
                ('cal_min', models.IntegerField()),
                ('cal_max', models.IntegerField()),
                ('protein_min', models.IntegerField()),
                ('protein_max', models.IntegerField()),
                ('fat_min', models.IntegerField()),
                ('fat_max', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
