# Generated by Django 4.1.7 on 2024-03-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customter',
            new_name='Customer',
        ),
    ]
